name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - "main"

jobs:
  tests:
    name: "ğŸ§ª Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-nodejs
      - run: |
          npm install
          just test

  build:
    name: "ğŸ”¨ Build Client"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-nodejs
      - run: |
          npm install
          just build
      - uses: actions/upload-artifact@v4
        with:
          name: client
          path: ${{ github.workspace }}/client/dist/**/*
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  deploy:
    name: "ğŸ¢ Deploy to AWS"
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-nodejs
      - uses: ./.github/actions/setup-terraform
      - uses: actions/download-artifact@v4
        with:
          name: client
          path: client/dist
      - run: |
          ls -l 
          ls -l client
          ls -l client/dist
