name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - "main"

jobs:
  tests:
    name: "ðŸ§ª Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-nodejs
      - run: |
          npm install
          just test

  build:
    name: "ðŸ”¨ Build Client"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-nodejs
      - run: |
          npm install
          just build
      - uses: actions/upload-artifact@v4
        with:
          name: client
          path: ${{ github.workspace }}/client/dist/**/*
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  deploy:
    name: "ðŸŽ¢ Deploy to AWS"
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just
      - uses: ./.github/actions/setup-nodejs
      - uses: ./.github/actions/setup-terraform
      - uses: actions/download-artifact@v4
        with:
          name: client
          path: client/dist
      - run: |
          just deploy --auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
